// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function FetchProjects(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function FrontendLog(arg1:string,arg2:Record<string, any>):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetTickets():Promise<Array<main.Ticket>>;

export function GetYouTrackToken():Promise<string>;

export function HideWindow():Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveYouTrackToken(arg1:string):Promise<void>;

export function SyncTickets():Promise<Array<main.Ticket>>;

export function ValidateYouTrackToken(arg1:string,arg2:string):Promise<boolean>;
