// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function FetchProjects(arg1, arg2) {
  return window['go']['main']['App']['FetchProjects'](arg1, arg2);
}

export function FrontendLog(arg1, arg2) {
  return window['go']['main']['App']['FrontendLog'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentUser(arg1, arg2) {
  return window['go']['main']['App']['GetCurrentUser'](arg1, arg2);
}

export function GetTickets() {
  return window['go']['main']['App']['GetTickets']();
}

export function GetYouTrackToken() {
  return window['go']['main']['App']['GetYouTrackToken']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveYouTrackToken(arg1) {
  return window['go']['main']['App']['SaveYouTrackToken'](arg1);
}

export function SyncTickets() {
  return window['go']['main']['App']['SyncTickets']();
}

export function ValidateYouTrackToken(arg1, arg2) {
  return window['go']['main']['App']['ValidateYouTrackToken'](arg1, arg2);
}
